#!/usr/bin/env python3
"""Pack the approved plate HUD background and value glyphs for the live host."""

from pathlib import Path
import sys

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "doom/tools/prototypes"))
from hud_playback_candidates import PANEL, REF, nearest, value_glyphs  # noqa: E402


def c_array(name: str, data: bytes) -> str:
    lines = [f"static const uint8_t {name}[{len(data)}] = {{"]
    for start in range(0, len(data), 24):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in data[start:start + 24]) + ",")
    return "\n".join(lines + ["};", ""])


def main() -> None:
    target = np.asarray(Image.open(REF).convert("RGB"))
    panel = nearest(target[192:240], PANEL).copy()
    for x0, x1 in ((4, 31), (35, 74), (148, 182)):
        panel[6:22, x0:x1] = 1
    panel[4:44, 112:144] = 0  # black face well
    panel[6:30, 76:108] = 1  # weapon selection wells are drawn below
    panel[6:42, 183:194] = 1  # matching keycard wells
    for row in range(4):
        y = 6 + row * 9
        panel[y:y + 7, 220:256] = 1
    # The top row remains concrete; wells share the fixture's 9x10 geometry.
    for row in range(2):
        for col in range(3):
            x, y = 77 + col * 10, 7 + row * 12
            panel[y:y + 10, x:x + 9] = 0
            panel[y, x:x + 9] = 2
            panel[y + 9, x:x + 9] = 2
            panel[y:y + 10, x] = 2
            panel[y:y + 10, x + 8] = 2
    for row in range(3):
        y = 7 + row * 12
        panel[y:y + 10, 183:193] = 0
        panel[y, 183:193] = 2
        panel[y + 9, 183:193] = 2
        panel[y:y + 10, 183] = 2
        panel[y:y + 10, 192] = 2
    # The v4 skipped row is now 232..239. Its face backing is set by native
    # text commands; the streamed panel ends at scanline 231.
    glyphs = value_glyphs(target)
    widths = bytes(glyphs[ch].shape[1] for ch in "0123456789%")
    glyph_data = bytearray()
    for ch in "0123456789%":
        glyph = glyphs[ch]
        tile = np.ones((15, 12), dtype=np.uint8)
        tile[:, :glyph.shape[1]] = glyph
        for row in tile:
            for x in range(0, 12, 4):
                glyph_data.append(sum(int(row[x + i]) << (i * 2) for i in range(4)))
    packed = bytearray()
    for row in panel:
        for x in range(0, 256, 4):
            packed.append(sum(int(row[x + i]) << (i * 2) for i in range(4)))
    output = ROOT / "doom/port/video/native_status_panel.h"
    output.write_text("/* Generated by doom/tools/build_live_hud_art.py. */\n"
                      "#ifndef NATIVE_STATUS_PANEL_H\n#define NATIVE_STATUS_PANEL_H\n"
                      "#include <stdint.h>\n"
                      + c_array("native_panel_pixels", packed)
                      + c_array("native_value_widths", widths)
                      + c_array("native_value_pixels", glyph_data)
                      + "#endif\n")
    print(f"{output}: {len(packed)} panel bytes, {len(glyph_data)} glyph bytes")


if __name__ == "__main__":
    main()
