#!/usr/bin/env python3
# SPDX-License-Identifier: BSD-3-Clause
"""Copy the permanent NES menu font's A-Z bitmaps into a C header."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
FIX_BANK = ROOT / "tutorial_project/BOOTROM/bootrom_fixr.bin"
OUTPUT = ROOT / "doom/port/video/native_menu_font.h"
BASE = 1921


def main() -> None:
    bank = FIX_BANK.read_bytes()
    rows = [bank[BASE + code * 8:BASE + (code + 1) * 8]
            for code in range(ord("A"), ord("Z") + 1)]
    assert rows[0] == bytes.fromhex("007cc6c6c6fec6c6")
    assert len(rows) == 26 and all(len(row) == 8 for row in rows)
    lines = ["/* SPDX-License-Identifier: BSD-3-Clause */",
             "/* Generated by doom/tools/build_native_menu_font.py from bootrom_fixr.bin. */",
             "#ifndef NATIVE_MENU_FONT_H", "#define NATIVE_MENU_FONT_H",
             "static const unsigned char native_menu_font[26][8] = {"]
    lines += ["    {" + ", ".join(f"0x{value:02x}" for value in row) + "},"
              for row in rows]
    lines += ["};", "#endif", ""]
    OUTPUT.write_text("\n".join(lines))
    print(f"menu font: {OUTPUT} ({len(rows)} glyphs)")


if __name__ == "__main__":
    main()
