# SPDX-License-Identifier: BSD-3-Clause
"""gen_protocol.py -- render fcbus/fcbus_protocol.h into generated outputs.

fcbus/fcbus_protocol.h is the single source of truth for the FC PICO <-> Famicom
wire protocol (plan decision D9, see doom/plan/03-protocol-v2.md). This script
parses that header and renders two generated files:

  - bootrom/gen/protocol.inc  -- nesasm 2.51 `EQU` lines for the boot ROM.
  - tools/fcpico/protocol.py  -- plain Python constants for tools and tests.

Header format (see the comment at the top of fcbus_protocol.h): every line of
the form

    #define NAME  <value-or-expression>   // comment

is exported, in order. An expression may use only `+ - * / ( ) << >>`,
decimal/hex integer literals, and the names of earlier `#define`s. Comment
blocks of the form `/* @section name   description */` mark groups; each
group becomes one section in the generated files.

Usage:
    python3 tools/gen_protocol.py            # write both generated files
    python3 tools/gen_protocol.py --check    # write nothing; exit 1 if stale

Paths are resolved relative to this script's own location (doom/), not the
current working directory, so it can be run from anywhere.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import re
import sys
from dataclasses import dataclass
from pathlib import Path

DOOM_ROOT = Path(__file__).resolve().parent.parent
HEADER_PATH = DOOM_ROOT / "fcbus" / "fcbus_protocol.h"
ASM_OUT_PATH = DOOM_ROOT / "bootrom" / "gen" / "protocol.inc"
PY_OUT_PATH = DOOM_ROOT / "tools" / "fcpico" / "protocol.py"

GENERATED_NOTE = (
    "GENERATED by tools/gen_protocol.py from fcbus/fcbus_protocol.h -- do not edit."
)

#: Extra nesasm-only spellings to emit as `EQU` aliases after the main constant
#: table, {alias_name: canonical_header_name}. The tutorial's boot ROM spells
#: PF_MAGIC_NO as PF_MAGIC_CODE; add further entries here if another alias is
#: ever needed.
ASM_ALIAS: dict[str, str] = {
    "PF_MAGIC_CODE": "PF_MAGIC_NO",
}


class ProtocolError(Exception):
    """A malformed or unsupported line in fcbus_protocol.h."""


# --------------------------------------------------------------------------
# Parsing
# --------------------------------------------------------------------------

_SECTION_RE = re.compile(r"/\*\s*@section\s+(\S+)\s+(.*?)\s*\*/\s*$")
_DEFINE_RE = re.compile(r"^\s*#define\s+([A-Za-z_]\w*)\s*(.*)$")


@dataclass(frozen=True)
class Section:
    name: str
    description: str


@dataclass(frozen=True)
class Definition:
    name: str
    raw_value: str  # value text exactly as written in the header, comment stripped
    value: int  # evaluated result
    comment: str  # trailing `//` comment, stripped, "" if none
    section: str  # @section name this definition falls under


def parse_header(text: str) -> tuple[list[Definition], list[Section]]:
    """Parse fcbus_protocol.h's #define/@section lines, in order."""
    known: dict[str, int] = {}
    defs: list[Definition] = []
    sections: list[Section] = []
    seen_sections: set[str] = set()
    current_section: str | None = None

    for lineno, line in enumerate(text.splitlines(), start=1):
        section_match = _SECTION_RE.search(line)
        if section_match:
            name, description = section_match.group(1), section_match.group(2)
            current_section = name
            if name not in seen_sections:
                seen_sections.add(name)
                sections.append(Section(name=name, description=description))
            continue

        code_part, _, comment_part = line.partition("//")
        define_match = _DEFINE_RE.match(code_part)
        if not define_match:
            continue

        name = define_match.group(1)
        raw_value = define_match.group(2).strip()
        if not raw_value:
            # e.g. the `#define FCBUS_PROTOCOL_H` include guard: no value, so
            # per the header's own contract it is not an exported constant.
            continue

        if current_section is None:
            raise ProtocolError(
                f"fcbus_protocol.h:{lineno}: {name} is defined before any "
                "'@section' marker"
            )

        comment = comment_part.strip()
        value = eval_expr(raw_value, name, known)
        known[name] = value
        defs.append(
            Definition(
                name=name,
                raw_value=raw_value,
                value=value,
                comment=comment,
                section=current_section,
            )
        )

    return defs, sections


# --------------------------------------------------------------------------
# Safe expression evaluator (ast whitelist -- never calls eval()/exec())
# --------------------------------------------------------------------------

_BINOPS = {
    ast.Add: lambda a, b: a + b,
    ast.Sub: lambda a, b: a - b,
    ast.Mult: lambda a, b: a * b,
    ast.Div: lambda a, b: _c_truncating_div(a, b),
    ast.LShift: lambda a, b: a << b,
    ast.RShift: lambda a, b: a >> b,
}
_UNARYOPS = {
    ast.UAdd: lambda a: a,
    ast.USub: lambda a: -a,
}


def _c_truncating_div(a: int, b: int) -> int:
    """Integer division truncating toward zero, like C's `/` on ints."""
    quotient = abs(a) // abs(b)
    return -quotient if (a < 0) != (b < 0) else quotient


def eval_expr(text: str, name: str, known: dict[str, int]) -> int:
    """Evaluate a header value expression without ever running arbitrary code.

    `text` may use only `+ - * / ( ) << >>`, decimal/hex integer literals, and
    names already present in `known`. We parse it with `ast` purely to get a
    syntax tree (ast.parse never executes anything) and then walk that tree
    ourselves, so any construct outside the whitelist below is rejected
    rather than evaluated.
    """
    try:
        tree = ast.parse(text, mode="eval")
    except SyntaxError as exc:
        raise ProtocolError(
            f"{name}: cannot parse value {text!r}: {exc}"
        ) from exc

    def _eval(node: ast.AST) -> int:
        if isinstance(node, ast.Expression):
            return _eval(node.body)
        if isinstance(node, ast.Constant):
            if isinstance(node.value, int) and not isinstance(node.value, bool):
                return node.value
            raise ProtocolError(
                f"{name}: literal {node.value!r} in {text!r} is not an integer"
            )
        if isinstance(node, ast.Name):
            if node.id not in known:
                raise ProtocolError(
                    f"{name}: {text!r} references {node.id!r}, which is not "
                    "defined earlier in fcbus_protocol.h"
                )
            return known[node.id]
        if isinstance(node, ast.BinOp):
            op = _BINOPS.get(type(node.op))
            if op is None:
                raise ProtocolError(
                    f"{name}: operator {type(node.op).__name__} in {text!r} "
                    "is not one of + - * / << >>"
                )
            return op(_eval(node.left), _eval(node.right))
        if isinstance(node, ast.UnaryOp):
            op = _UNARYOPS.get(type(node.op))
            if op is None:
                raise ProtocolError(
                    f"{name}: unary operator {type(node.op).__name__} in "
                    f"{text!r} is not allowed"
                )
            return op(_eval(node.operand))
        raise ProtocolError(
            f"{name}: {type(node).__name__} in {text!r} is not allowed "
            "(only + - * / ( ) << >>, integer literals and earlier NAMEs are)"
        )

    return _eval(tree)


# --------------------------------------------------------------------------
# Radix classification and literal formatting
# --------------------------------------------------------------------------

_HEX_TOKEN_RE = re.compile(r"0[xX][0-9A-Fa-f]+")
_ATOMIC_HEX_RE = re.compile(r"^0[xX][0-9A-Fa-f]+$")
_ATOMIC_DEC_RE = re.compile(r"^-?[0-9]+$")


def classify_radix(raw_value: str) -> tuple[bool, str | None]:
    """Return (is_hex, atomic_literal_text).

    atomic_literal_text is the exact source token when raw_value is a single
    literal (letting callers reuse it verbatim -- preserving digit width and
    case), and None when raw_value is an expression. For an expression,
    is_hex reports whether any hex literal token appears in it (an
    expression built only from earlier NAMEs and/or decimal literals is
    treated as decimal).
    """
    text = raw_value.strip()
    if _ATOMIC_HEX_RE.match(text):
        return True, text
    if _ATOMIC_DEC_RE.match(text):
        return False, text
    return bool(_HEX_TOKEN_RE.search(text)), None


def format_hex_digits(value: int) -> str:
    """Uppercase hex digits for `value`, padded to an even width >= 2."""
    digits = format(value, "X")
    if len(digits) % 2 == 1 or len(digits) < 2:
        digits = digits.rjust(len(digits) + 1 if len(digits) % 2 else 2, "0")
    return digits


def inc_literal(value: int, raw_value: str) -> str:
    """Render `value` as a nesasm literal for protocol.inc.

    Simplest rule (see the gen_protocol.py deliverable notes in
    doom/plan/03-protocol-v2.md): hex ($XX) for values < 0x10000 that were
    written in hex in the header; decimal otherwise. This keeps byte/word
    constants (opcodes, masks, offsets) in the hex the header already used,
    while large or decimally-written values (counts, sizes, cycle budgets)
    stay decimal.
    """
    is_hex, atomic = classify_radix(raw_value)
    if is_hex and value < 0x10000:
        if atomic is not None:
            return "$" + atomic[2:].upper()
        return "$" + format_hex_digits(value)
    if atomic is not None and not is_hex:
        return atomic
    return str(value)


def py_literal(value: int, raw_value: str) -> str:
    """Render `value` as a Python literal for protocol.py, preserving radix.

    Unlike inc_literal, there is no size cutoff: Python integers are not
    width-limited, so a value the header wrote in hex stays hex regardless
    of magnitude (e.g. the 32-bit FCBUS_VER_SYNC_W0/W1 sync words).
    """
    is_hex, atomic = classify_radix(raw_value)
    if is_hex:
        if atomic is not None:
            return "0x" + atomic[2:].upper()
        return "0x" + format_hex_digits(value)
    if atomic is not None:
        return atomic
    return str(value)


def validate_aliases(defs: list[Definition]) -> None:
    names = {d.name for d in defs}
    for alias, canonical in ASM_ALIAS.items():
        if canonical not in names:
            raise ProtocolError(
                f"ASM_ALIAS: {alias!r} points at {canonical!r}, which is not "
                "defined in fcbus_protocol.h"
            )
        if alias in names:
            raise ProtocolError(
                f"ASM_ALIAS: alias {alias!r} collides with a real name "
                "already defined in fcbus_protocol.h"
            )


# --------------------------------------------------------------------------
# Rendering
# --------------------------------------------------------------------------


def _section_header(prefix: str, section: str, description: str) -> str:
    if description:
        return f"{prefix} --- {section}: {description} ---"
    return f"{prefix} --- {section} ---"


def render_asm(defs: list[Definition], sections: list[Section]) -> str:
    sec_desc = {s.name: s.description for s in sections}
    lines: list[str] = [
        "; SPDX-License-Identifier: BSD-3-Clause",
        ";",
        f"; {GENERATED_NOTE}",
    ]

    current_section: str | None = None
    for d in defs:
        if d.section != current_section:
            current_section = d.section
            lines.append(";")
            lines.append(
                _section_header(";", current_section, sec_desc.get(current_section, ""))
            )
        literal = inc_literal(d.value, d.raw_value)
        line = f"{d.name}\tEQU\t{literal}"
        if d.comment:
            line += f"\t; {d.comment}"
        lines.append(line)

    if ASM_ALIAS:
        lines.append(";")
        lines.append("; --- nesasm aliases (ASM_ALIAS in gen_protocol.py) ---")
        for alias_name, canonical in ASM_ALIAS.items():
            lines.append(f"{alias_name}\tEQU\t{canonical}")

    return "\n".join(lines) + "\n"


def _format_section_map(sections_out: dict[str, list[str]]) -> str:
    if not sections_out:
        return "{}"
    rows = [
        "    {!r}: [{}],".format(name, ", ".join(repr(m) for m in members))
        for name, members in sections_out.items()
    ]
    return "{\n" + "\n".join(rows) + "\n}"


def _format_str_map(mapping: dict[str, str]) -> str:
    if not mapping:
        return "{}"
    rows = [f"    {k!r}: {v!r}," for k, v in mapping.items()]
    return "{\n" + "\n".join(rows) + "\n}"


def _format_all_map(defs: list[Definition]) -> str:
    rows = [f"    {d.name!r}: {d.name}," for d in defs]
    return "{\n" + "\n".join(rows) + "\n}"


def render_py(defs: list[Definition], sections: list[Section]) -> str:
    sec_desc = {s.name: s.description for s in sections}
    sections_out: dict[str, list[str]] = {}

    lines: list[str] = [
        "# SPDX-License-Identifier: BSD-3-Clause",
        "#",
        f"# {GENERATED_NOTE}",
        '"""FC PICO <-> Famicom wire protocol constants; see fcbus/fcbus_protocol.h."""',
    ]

    current_section: str | None = None
    for d in defs:
        if d.section != current_section:
            current_section = d.section
            lines.append("")
            lines.append(
                _section_header("#", current_section, sec_desc.get(current_section, ""))
            )
        sections_out.setdefault(d.section, []).append(d.name)
        literal = py_literal(d.value, d.raw_value)
        line = f"{d.name} = {literal}"
        if d.comment:
            line += f"  # {d.comment}"
        lines.append(line)

    lines.append("")
    lines.append("")
    lines.append("SECTIONS: dict[str, list[str]] = " + _format_section_map(sections_out))
    lines.append("")
    lines.append("ASM_ALIASES: dict[str, str] = " + _format_str_map(ASM_ALIAS))
    lines.append("")
    lines.append("ALL: dict[str, int] = " + _format_all_map(defs))

    return "\n".join(lines) + "\n"


def generate() -> tuple[str, str]:
    """Return (asm_text, py_text) rendered from the current header on disk."""
    header_text = HEADER_PATH.read_text(encoding="utf-8")
    defs, sections = parse_header(header_text)
    validate_aliases(defs)
    return render_asm(defs, sections), render_py(defs, sections)


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="gen_protocol.py",
        description=(
            "Render fcbus/fcbus_protocol.h into bootrom/gen/protocol.inc and "
            "tools/fcpico/protocol.py."
        ),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="write nothing; exit 1 if either generated file would change",
    )
    args = parser.parse_args(argv)

    try:
        asm_text, py_text = generate()
    except ProtocolError as exc:
        print(f"gen_protocol.py: {exc}", file=sys.stderr)
        return 2

    outputs = ((ASM_OUT_PATH, asm_text), (PY_OUT_PATH, py_text))

    if args.check:
        fresh = True
        for path, content in outputs:
            existing = path.read_text(encoding="utf-8") if path.exists() else ""
            if existing != content:
                fresh = False
                rel = path.relative_to(DOOM_ROOT)
                print(f"stale: {rel}", file=sys.stderr)
                diff = difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile=f"{rel} (on disk)",
                    tofile=f"{rel} (generated)",
                )
                sys.stderr.writelines(diff)
        if not fresh:
            print(
                "gen_protocol.py --check: generated files are stale; run "
                "`python3 tools/gen_protocol.py` to refresh them.",
                file=sys.stderr,
            )
            return 1
        return 0

    for path, content in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
