# SPDX-License-Identifier: BSD-3-Clause
#
# GENERATED by tools/gen_protocol.py from fcbus/fcbus_protocol.h -- do not edit.
"""FC PICO <-> Famicom wire protocol constants; see fcbus/fcbus_protocol.h."""

# --- mailbox-v1: cartridge -> console, on the tail of the frame stream ---
PF_MAGIC_NO = 0xFC  # mailbox[1] validity sentinel (asm: PF_MAGIC_CODE)
PF_COM_NONE = 0x00  # end of command list
PF_COM_DMOD = 0x01  # blank display, enter bulk data mode
PF_COM_FDIN = 0x02  # palette fade in
PF_COM_FDOT = 0x03  # palette fade out
PF_COM_SE = 0x80  # 0x80|n play sound effect n (disabled in tutorial ROM)
PF_COM_BGM = 0xA0  # 0xA0|n play music n (disabled in tutorial ROM)
PF_COM_VRAM = 0xC0  # 0xC0|adrH, adrL, data: poke one VRAM byte
PF_DAT_VRAM = 0x80  # bulk data mode: VRAM block
PF_DAT_RAM = 0x81  # bulk data mode: CPU RAM block
PF_DAT_STEP = 0x82  # bulk data mode: leave and switch console step
FC_COM_BUF_SIZE16 = 16  # bytes of the mailbox the v1 command executor parses (2..15)
FC_COM_BUF_SIZE_V1 = 64  # v1 mailbox length appended to every frame
PICO_SNDREG = 0x10  # offset of the APU (reg,value) pair area in the mailbox
PICO_APU_BUF_SIZE = 0x40  # depth of the firmware's APU write ring (v1 firmware)
APU_PAIRS_MAX_V1 = 23  # pairs that fit: (64 - 16 - 2) / 2, terminator 0xFF
APU_PAIRS_MAX_NMI_V1 = 24  # pairs the tutorial NMI replay loop will apply (0x30 bytes)

# --- opcodes-v1: console -> cartridge, single bytes written to $2007 ---
FP_COM_ACK = 0x0F  # unused on both sides
FP_COM_NAK = 0x1F  # unused on both sides
FP_COM_VER = 0x2F  # request the 14-byte boot-ROM build stamp
FP_COM_ROM = 0x3F  # + page: request 256 bytes of the boot ROM image
FP_COM_LOG = 0xBF  # + up to 7 bytes: print on the cartridge serial console
FP_COM_DRQ = 0xCF  # bulk data mode: request next block header
FP_COM_DLD = 0xDF  # + page: bulk data mode: request one 256-byte page
FP_COM_RST = 0xEF  # restart the cartridge firmware
FP_COM_INI = 0xFF  # + stage: initialise the cartridge

# --- keys: controller byte bit layout (both directions) ---
KEY_A = 0x80
KEY_B = 0x40
KEY_SEL = 0x20
KEY_RUN = 0x10  # Start
KEY_UP = 0x08
KEY_DOWN = 0x04
KEY_LEFT = 0x02
KEY_RIGHT = 0x01

# --- stream: frame stream geometry (empirical, from the tutorial) ---
PPU_PICTURE_COUNT = 15426  # qualifying PPU reads consumed before the mailbox (empirical)
PPU_COUNT_WINDOW = 2  # +/- reads tolerated before the DMA is stopped
PPU_COUNT_VAL_V1 = 15490  # 15490
VRAM_LINE_WORDS = 34  # 16-bit words per scanline in the stream buffer
VRAM_HEAD_WORDS = 31  # word index of line 0, tile 0
VRAM_LINES = 240
VRAM_TILE_COLS = 32  # visible tiles per line; words 32,33 = next line's first 16 px
VRAM_BUF_BYTES_V1 = 17344  # 17344, DMA length in bytes
VRAM_MAILBOX_OFF_V1 = 15426  # 15426: mailbox byte offset in the buffer
FCBUS_VER_SYNC_W0 = 0x21212121  # "!!!!" pushed before the version stamp
FCBUS_VER_SYNC_W1 = 0x43462321  # "!#FC" little-endian; the fix bank syncs on 'C'
FCBUS_ROM_STAMP_OFF = 0x6FF0  # stamp offset within the 32 KB PRG image ($EFF0)
FCBUS_ROM_STAMP_LEN = 14  # bytes compared by CHK_ROMVER (16 streamed)
FCBUS_ROM_PRG_BYTES = 0x8000
FCBUS_ROM_INES_HDR = 16
FCBUS_DRQ_MAGIC_BASE = 0xFC00  # drq_ret(): word0 = base + com + (adr << 16), word1 = size

# --- v2: Doom boot ROM protocol (superset) ---
FCBUS_PROTOCOL_V2 = 2
FP_COM_KEY = 0x4F  # + pad1, pad2: controller packet = the v2 heartbeat
FP_COM_HELLO = 0x5F  # + version: sent once after FP_COM_INI by a v2 boot ROM
FC_COM_BUF_SIZE_V2 = 128  # v2 mailbox length
PPU_COUNT_VAL_V2 = 15554  # 15554
VRAM_BUF_BYTES_V2 = 17408  # 17408
VRAM_MAILBOX_OFF_V2 = 15426  # 15426 (same tail position)
MBX_FLAGS = 0  # byte 0: flags (v1: unused)
MBX_MAGIC = 1  # byte 1: PF_MAGIC_NO
MBX_CMD = 2  # bytes 2..15: command list, PF_COM_NONE terminated
MBX_CMD_LEN = 14
MBX_APU = 16  # bytes 16..47: (reg,value) pairs, 0xFF terminated
MBX_APU_LEN = 32
APU_PAIRS_MAX_V2 = 15  # (32 - 2) / 2 pairs leave room for the terminator
MBX_PAL = 48  # bytes 48..63: BG palette $3F00-$3F0F
MBX_PAL_LEN = 16
MBX_ATTR = 64  # bytes 64..127: attribute table $23C0-$23FF
MBX_ATTR_LEN = 64
MBX_FLAG_ATTR_VALID = 0x01
MBX_FLAG_PAL_VALID = 0x02
MBX_FLAG_APU_VALID = 0x04
MBX_FLAG_V2 = 0x80
MBX_ZP_LO = 0x20  # console zero page holding mailbox bytes 0..63
MBX_ZP_HI = 0xC0  # console zero page holding mailbox bytes 64..127
NMI_CRITICAL_CYCLES_MAX = 1900  # budget for the vblank-critical part of the v2 NMI
NMI_TOTAL_CYCLES_MAX = 2200  # budget for the whole v2 NMI (NTSC vblank = 2273)


SECTIONS: dict[str, list[str]] = {
    'mailbox-v1': ['PF_MAGIC_NO', 'PF_COM_NONE', 'PF_COM_DMOD', 'PF_COM_FDIN', 'PF_COM_FDOT', 'PF_COM_SE', 'PF_COM_BGM', 'PF_COM_VRAM', 'PF_DAT_VRAM', 'PF_DAT_RAM', 'PF_DAT_STEP', 'FC_COM_BUF_SIZE16', 'FC_COM_BUF_SIZE_V1', 'PICO_SNDREG', 'PICO_APU_BUF_SIZE', 'APU_PAIRS_MAX_V1', 'APU_PAIRS_MAX_NMI_V1'],
    'opcodes-v1': ['FP_COM_ACK', 'FP_COM_NAK', 'FP_COM_VER', 'FP_COM_ROM', 'FP_COM_LOG', 'FP_COM_DRQ', 'FP_COM_DLD', 'FP_COM_RST', 'FP_COM_INI'],
    'keys': ['KEY_A', 'KEY_B', 'KEY_SEL', 'KEY_RUN', 'KEY_UP', 'KEY_DOWN', 'KEY_LEFT', 'KEY_RIGHT'],
    'stream': ['PPU_PICTURE_COUNT', 'PPU_COUNT_WINDOW', 'PPU_COUNT_VAL_V1', 'VRAM_LINE_WORDS', 'VRAM_HEAD_WORDS', 'VRAM_LINES', 'VRAM_TILE_COLS', 'VRAM_BUF_BYTES_V1', 'VRAM_MAILBOX_OFF_V1', 'FCBUS_VER_SYNC_W0', 'FCBUS_VER_SYNC_W1', 'FCBUS_ROM_STAMP_OFF', 'FCBUS_ROM_STAMP_LEN', 'FCBUS_ROM_PRG_BYTES', 'FCBUS_ROM_INES_HDR', 'FCBUS_DRQ_MAGIC_BASE'],
    'v2': ['FCBUS_PROTOCOL_V2', 'FP_COM_KEY', 'FP_COM_HELLO', 'FC_COM_BUF_SIZE_V2', 'PPU_COUNT_VAL_V2', 'VRAM_BUF_BYTES_V2', 'VRAM_MAILBOX_OFF_V2', 'MBX_FLAGS', 'MBX_MAGIC', 'MBX_CMD', 'MBX_CMD_LEN', 'MBX_APU', 'MBX_APU_LEN', 'APU_PAIRS_MAX_V2', 'MBX_PAL', 'MBX_PAL_LEN', 'MBX_ATTR', 'MBX_ATTR_LEN', 'MBX_FLAG_ATTR_VALID', 'MBX_FLAG_PAL_VALID', 'MBX_FLAG_APU_VALID', 'MBX_FLAG_V2', 'MBX_ZP_LO', 'MBX_ZP_HI', 'NMI_CRITICAL_CYCLES_MAX', 'NMI_TOTAL_CYCLES_MAX'],
}

ASM_ALIASES: dict[str, str] = {
    'PF_MAGIC_CODE': 'PF_MAGIC_NO',
}

ALL: dict[str, int] = {
    'PF_MAGIC_NO': PF_MAGIC_NO,
    'PF_COM_NONE': PF_COM_NONE,
    'PF_COM_DMOD': PF_COM_DMOD,
    'PF_COM_FDIN': PF_COM_FDIN,
    'PF_COM_FDOT': PF_COM_FDOT,
    'PF_COM_SE': PF_COM_SE,
    'PF_COM_BGM': PF_COM_BGM,
    'PF_COM_VRAM': PF_COM_VRAM,
    'PF_DAT_VRAM': PF_DAT_VRAM,
    'PF_DAT_RAM': PF_DAT_RAM,
    'PF_DAT_STEP': PF_DAT_STEP,
    'FC_COM_BUF_SIZE16': FC_COM_BUF_SIZE16,
    'FC_COM_BUF_SIZE_V1': FC_COM_BUF_SIZE_V1,
    'PICO_SNDREG': PICO_SNDREG,
    'PICO_APU_BUF_SIZE': PICO_APU_BUF_SIZE,
    'APU_PAIRS_MAX_V1': APU_PAIRS_MAX_V1,
    'APU_PAIRS_MAX_NMI_V1': APU_PAIRS_MAX_NMI_V1,
    'FP_COM_ACK': FP_COM_ACK,
    'FP_COM_NAK': FP_COM_NAK,
    'FP_COM_VER': FP_COM_VER,
    'FP_COM_ROM': FP_COM_ROM,
    'FP_COM_LOG': FP_COM_LOG,
    'FP_COM_DRQ': FP_COM_DRQ,
    'FP_COM_DLD': FP_COM_DLD,
    'FP_COM_RST': FP_COM_RST,
    'FP_COM_INI': FP_COM_INI,
    'KEY_A': KEY_A,
    'KEY_B': KEY_B,
    'KEY_SEL': KEY_SEL,
    'KEY_RUN': KEY_RUN,
    'KEY_UP': KEY_UP,
    'KEY_DOWN': KEY_DOWN,
    'KEY_LEFT': KEY_LEFT,
    'KEY_RIGHT': KEY_RIGHT,
    'PPU_PICTURE_COUNT': PPU_PICTURE_COUNT,
    'PPU_COUNT_WINDOW': PPU_COUNT_WINDOW,
    'PPU_COUNT_VAL_V1': PPU_COUNT_VAL_V1,
    'VRAM_LINE_WORDS': VRAM_LINE_WORDS,
    'VRAM_HEAD_WORDS': VRAM_HEAD_WORDS,
    'VRAM_LINES': VRAM_LINES,
    'VRAM_TILE_COLS': VRAM_TILE_COLS,
    'VRAM_BUF_BYTES_V1': VRAM_BUF_BYTES_V1,
    'VRAM_MAILBOX_OFF_V1': VRAM_MAILBOX_OFF_V1,
    'FCBUS_VER_SYNC_W0': FCBUS_VER_SYNC_W0,
    'FCBUS_VER_SYNC_W1': FCBUS_VER_SYNC_W1,
    'FCBUS_ROM_STAMP_OFF': FCBUS_ROM_STAMP_OFF,
    'FCBUS_ROM_STAMP_LEN': FCBUS_ROM_STAMP_LEN,
    'FCBUS_ROM_PRG_BYTES': FCBUS_ROM_PRG_BYTES,
    'FCBUS_ROM_INES_HDR': FCBUS_ROM_INES_HDR,
    'FCBUS_DRQ_MAGIC_BASE': FCBUS_DRQ_MAGIC_BASE,
    'FCBUS_PROTOCOL_V2': FCBUS_PROTOCOL_V2,
    'FP_COM_KEY': FP_COM_KEY,
    'FP_COM_HELLO': FP_COM_HELLO,
    'FC_COM_BUF_SIZE_V2': FC_COM_BUF_SIZE_V2,
    'PPU_COUNT_VAL_V2': PPU_COUNT_VAL_V2,
    'VRAM_BUF_BYTES_V2': VRAM_BUF_BYTES_V2,
    'VRAM_MAILBOX_OFF_V2': VRAM_MAILBOX_OFF_V2,
    'MBX_FLAGS': MBX_FLAGS,
    'MBX_MAGIC': MBX_MAGIC,
    'MBX_CMD': MBX_CMD,
    'MBX_CMD_LEN': MBX_CMD_LEN,
    'MBX_APU': MBX_APU,
    'MBX_APU_LEN': MBX_APU_LEN,
    'APU_PAIRS_MAX_V2': APU_PAIRS_MAX_V2,
    'MBX_PAL': MBX_PAL,
    'MBX_PAL_LEN': MBX_PAL_LEN,
    'MBX_ATTR': MBX_ATTR,
    'MBX_ATTR_LEN': MBX_ATTR_LEN,
    'MBX_FLAG_ATTR_VALID': MBX_FLAG_ATTR_VALID,
    'MBX_FLAG_PAL_VALID': MBX_FLAG_PAL_VALID,
    'MBX_FLAG_APU_VALID': MBX_FLAG_APU_VALID,
    'MBX_FLAG_V2': MBX_FLAG_V2,
    'MBX_ZP_LO': MBX_ZP_LO,
    'MBX_ZP_HI': MBX_ZP_HI,
    'NMI_CRITICAL_CYCLES_MAX': NMI_CRITICAL_CYCLES_MAX,
    'NMI_TOTAL_CYCLES_MAX': NMI_TOTAL_CYCLES_MAX,
}
