#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Prove that documenting the tree did not change the tree's behaviour.

Every file under ``tutorial_project/`` is compared against its committed
version with comments and whitespace stripped.  A difference means real code
moved, which is exactly what the documentation pass is not allowed to do.

Usage::

    python tools/doxygen/check_code_unchanged.py [git-ref]

``git-ref`` defaults to ``HEAD``.  Exits non-zero if any file differs, so the
script can gate a commit.

One file is expected to differ and is listed explicitly:

- ``mml/env_set0.mmh`` -- full-width ``｛｝`` normalised to ASCII braces so the
  file survives transcoding to UTF-8.  Verified by rebuilding ``sound.nsf``.

Assembler output (``*.lst``, ``*.log``) is skipped and counted separately; see
``GENERATED``.
"""

import re
import subprocess
import sys
import os

## Files whose *code* legitimately differs, with the reason.
ALLOWED = {
    "tutorial_project/mml/env_set0.mmh": "full-width braces normalised to ASCII",
}

## Generated by nesasm; regenerated on every build.  Never hand-edited and never
## transcoded -- they inherit whatever encoding the sources had at build time, so
## comparing them for code equality is meaningless.  Listed explicitly rather than
## left to fall through the LINE_COMMENTS lookup, because a silent skip is what
## let a double-encoding defect sit in both PG_main.lst files unnoticed.
GENERATED = {".lst", ".log"}

## Comment syntax per file kind: (line-comment tokens, block-comment pairs).
LINE_COMMENTS = {
    ".asm": [";"],
    ".pio": [";"],
    ".h": ["//", ";"],      # C headers and nesasm includes share the extension
    ".c": ["//"],
    ".cpp": ["//"],
    ".ino": ["//"],
    ".mml": ["//", ";"],
    ".mmh": ["//", ";"],
    ".nut": ["//"],
    ".af": ["//"],
    ".bat": ["::", "rem ", "REM "],
}


def strip_comments(text, ext):
    """Reduce *text* to just its executable content.

    Block comments are removed first, then line comments, then all whitespace is
    collapsed, so that reflowing or re-indenting a file cannot register as a
    change.

    @param text full file contents.
    @param ext lowercase file extension, used to pick the comment syntax.
    @return a normalised string safe to compare for equality.
    """
    if ext in (".c", ".cpp", ".h", ".ino", ".nut", ".af", ".mml", ".mmh"):
        text = re.sub(r"/\*.*?\*/", " ", text, flags=re.S)

    tokens = LINE_COMMENTS.get(ext, ["//"])
    out = []
    for line in text.split("\n"):
        cut = len(line)
        for tok in tokens:
            # A ';' inside a quoted string is not a comment; the tree has only
            # one such case (dbdate.h) and it contains no ';', so a plain scan
            # is sufficient here.
            idx = line.find(tok)
            if idx != -1:
                cut = min(cut, idx)
        out.append(line[:cut])
    return re.sub(r"\s+", "", "\n".join(out))


def decode(data):
    """Decode *data* the same way on both sides of the comparison.

    The tree is UTF-8, but files that arrived from upstream after the
    conversion may still be CP932.  Both sides must use the same rule or a
    CP932 file compares unequal against itself: decoding one side as UTF-8 with
    replacement turns every Japanese byte into U+FFFD, and any such byte
    outside a comment then reads as a code change that never happened.

    @param data raw file bytes.
    @return the decoded text.
    """
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError:
        return data.decode("cp932", errors="replace")


def main(argv):
    """Compare every tracked source file against *git-ref*.

    @param argv process argument vector; ``argv[1]`` optionally names a git ref.
    @return 0 if only comments changed, 1 otherwise.
    """
    ref = argv[1] if len(argv) > 1 else "HEAD"
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    os.chdir(root)

    files = subprocess.run(
        ["git", "ls-files", "tutorial_project"],
        capture_output=True, text=True, check=True,
    ).stdout.split()

    checked = differing = skipped = 0
    for path in files:
        ext = os.path.splitext(path)[1].lower()
        if ext in GENERATED:
            skipped += 1
            continue
        if ext not in LINE_COMMENTS:
            continue

        old = subprocess.run(
            ["git", "show", "%s:%s" % (ref, path)],
            capture_output=True, check=False,
        )
        if old.returncode != 0:
            continue

        old_text = decode(old.stdout)

        with open(path, "rb") as fh:
            new_text = decode(fh.read())

        checked += 1
        if strip_comments(old_text, ext) != strip_comments(new_text, ext):
            note = ALLOWED.get(path.replace("\\", "/"))
            if note:
                print("  expected: %s  (%s)" % (path, note))
            else:
                print("  CODE CHANGED: %s" % path)
                differing += 1

    print("\nchecked %d files, skipped %d generated, %d unexpected code changes"
          % (checked, skipped, differing))
    return 1 if differing else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
